#
# 修繕設定ファイル
#
#修繕対象のアイテムを設定するファイルです。
#「ITEMS:」をラベルにした、子要素のマッピングされた"英字"のアイテム名を読み込みます。
#bukkitに存在しないアイテム名の場合は無視されます。
#
#書式:「KEY: "ITEMNAME"」（KEYは他要素と被らないキーワード）
#
#例:
#ITEMS:
#  ITEM1: "ELYTRA"
#  ITEM2: "TRIDENT"
#
#
ITEMS:
  ITEM1: "ELYTRA"
  ITEM2: "TRIDENT"